### ISSUE TITLE
Copy an element's JavaScript path

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#32]
I think this is also available in Firefox & Safari, albeit named differently, which copies the CSS selector, and can then be used in `document.querySelector(<path>)`. I'm not sure if you're planning to have a separate feature to copy CSS selector.

![copy-js-path-firefox](https://user-images.githubusercontent.com/38640616/180640196-11d337d4-c5dc-42cb-81f6-5b96d39b05ae.gif)

**Comment by captainbrosset** [comment]
Thanks a lot! And great point. I think I'd prefer creating a separate tip for copying css selectors, in all browsers. 
Also because there are 2 types of CSS selectors, at least in Firefox: Path and Selector. With one being unique and the other not.

Any interest in opening a PR yourself to do this @pankajparashar by the way? If not I'll do it.

**Comment by pankajparashar** [comment]
Sure, I'll open a PR :-)

**Comment by captainbrosset** [comment]
Awesome! Thanks so much,

**Comment by captainbrosset** [comment]
New tip is now live: https://devtoolstips.org/tips/en/copy-css-selector/
