### ISSUE TITLE
Chrome supports other languages for DevTools

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#39]
Re: https://devtoolstips.org/tips/en/use-another-language/

Chrome has pretty wide support for non-English languages. Arguably more than any other browser vendor. Should we add Chrome in the list of supported browsers?

![image](https://user-images.githubusercontent.com/38640616/193459676-e911daa5-55c1-422a-9279-cf5217e4e37c.png)

**Comment by pankajparashar** [comment]
It's also probably misleading to say that Firefox allows devs to change the language of the DevTools, if we were to rely on the title, isn't it?

Technically I haven't found a way to change Firefox's devtools language to some other language like Chrome & Edge does.

**Comment by captainbrosset** [comment]
Those are great points Pankaj. We should definitely add Chrome to the list of supported browsers here. When I created this tip, only Edge supported the feature, but then the code was contributed upstream to Chromium, and Chrome used it to roll out its own set of translated strings.

As for Firefox, the only way is to change the language of the entire browser. So, it is possible, but not as simple as with Chrome/Edge for sure.

I would still like to keep it mentioned here. For a long time, Firefox was the only browser to support DevTools localization, and because the browser is translated in many languages, this made it possible for many people to use devtools in their own languages.

I hear your point about the title being misleading and would be ok changing it from "Switch DevTools to another language" to "Use DevTools in another language". But I do want to keep Firefox in there because the whole point of the tip is to help people use DevTools in a language that's more comfortable to them.

**Comment by pankajparashar** [comment]
Alright, with that reasoning, it is also possible to change language for Safari as well, using OS-level settings for app specific language (see s/s below). Hence, we should add Safari as well in this list. Agreed?

<img width="1188" alt="Screenshot 2022-10-03 at 14 22 42" src="https://user-images.githubusercontent.com/38640616/193537951-ab82daa1-9b3b-4ed6-a8b7-c3f3601fa326.png">

**Comment by captainbrosset** [comment]
Yes, good point, we should also add Safari with these instructions.

**Comment by pankajparashar** [comment]
Fixed in #40
